version: '3.8'

services:
  text-generation:
    image: ghcr.io/huggingface/text-generation-inference:2.0.3
    shm_size: '1g'
    ports:
      - '8080:80'
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    command: ["--model-id", "meta-llama/Llama-3.2-1B"]
