site_name: llmtranslate

theme:
  name: material

repo_url: https://github.com/adam-pawelek/llmtranslate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.mark
  - attr_list
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.keys
  - pymdownx.betterem
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.mark